baseURL = "https://simitclub.com/"
title = "The ITC Blog"
copyright = "Copyright © 2020, SIM Information Technology Club <br> All rights reserved."
paginate = 2
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-184206775-1"
DisqusShortname = "sim-it-club"
theme = "hugo-theme-chunky-poster"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "https://simitclub.com/#home"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 0

  

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"

[params]
  author = "Hugo Authors"
  description = "The SIM IT Club Blog"
  homepageImage = "/images/logo-wh.png"
  share = false
  showLanguageSwitcher = false
  

  # Custom CSS and JS. Relative to /static/css and /static/js respectively.
  customCSS = ["custom.css"]
  customJS = ["custom.js"]

  [params.social]
    # rss = true
    email = "example@example.com"
    facebook = "https://facebook.com"
    twitter = "https://twitter.com"
    linkedin = "https://linkedin.com"
    # stack-overflow = "https://stackoverflow.com"
    instagram = "https://stackoverflow.com"
    # github = "https://github.com"
    # weibo = "https://www.weibo.com"
    # medium = "https://medium.com"
    # pinterest = "https://pinterest.com"
    # reddit = "https://reddit.com"
    # gitlab = "https://gitlab.com"
    # mastodon = "https://mastodon.social"
    # keybase = "https://keybase.io/"

  [params.prismJS]
    enable = true
    theme = "okaidia"

  [params.commento]
    enable = true
    url = "https://commento.io"

[markup]
  [markup.highlight]
    codeFences = false

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
